### ISSUE TITLE
e-magyar.hu parser működése

### ISSUE THREAD

**Issue by kbalint** [dlt-rilmta/e-magyar.hu#3]
Próbálgatom a https://e-magyar.hu/hu/parser oldalon a tokenizert és a taggert, de furcsa eredményeket kapok. 

A bemenet mindig az a szó, hogy "látogatóközpontjának", és mindegyik futásra gyakorlatilag más lemmát hoz fel. néha "eltalálja" az eredetit (látogatóközpont), az esetek nagy részében meg valami vad dolog jön:

run 1)

id	emToken	emMorph	emLem	emTag
0	látogatóközpontjának			látogatóközpont
[/N][Poss.3Sg][Dat]
N

(ez jó, ezt vártam)

run 2)

id	emToken	emMorph	emLem	emTag
látogatóközpontjának

al[/CmpdPfx] + apa[/N]=ap + ja[Poss.3Sg] + [Nom]
alap[/N] + ja[Poss.3Sg] + [Nom]

alapa
alap

alap
[/N][Poss.3Sg][Nom]
N

run 3)

id	emToken	emMorph	emLem	emTag
0	látogatóközpontjának	
tesz[/V]=te + het[_Mod/V]=hes + senek[Sbjv.NDef.3Pl]
tesz
tesz
[/V][_Mod/V][Sbjv.NDef.3Pl]
V

Ez a működés minek az eredménye lehet? 

Ugyanígy ha hosszabb szöveget postolok, akkor úgy néz ki, mintha az onmouseover elemzés el lenne csúszva egy szóval (position-1).

**Comment by tamvar** [comment]
Tisztelt Kardos Bálint!

Köszönjük a jelzését. Kollégám megvizsgálta az ügyet, és ezek a vad dolgok
valóban abból származnak, hogy valami okból a pipe-on elromlott a kérdések
és a válaszok összehangja.
Újraindítottuk a szervert, és megszűnt a probléma.
Remélem, ezt Ön is így tapasztalja, és csak pillanatnyi üzemzavarról volt
szó.

Üdvözlettel,
VT
ᐧ

2018-01-02 20:29 GMT+01:00 Balint Kardos <notifications@github.com>:
